namespace Space_Wars.Content.Main;

public enum ModuleType
{
    Hull,
    Guns,
    Engines,
    Sensors,
    Core,
}
public enum Modules
{
    //Hulls
    Hull,
    Shield,
    Stealth,
    Reflective,
    Turtle,
    Ablative,
    Adaptive,
    ThermalShield,
    //Engines
    Engines,
    Plasma,
    Work,
    Orion,
    //Sensors
    Sensors,
    Lidar,
    Radar,
    PulseEmitter,
    //Weapons
    Basic,
    Spiral,
    Shotgun,
    Missile,
    LMG,
    Sniper,
    Crossbow,
    Flamethrower,
    Fireball,
    GrenadeLauncher,
    Spewer,
    Antimaterial,
    PrismArray,
    MatrixLauncher,
    Torch,
    Decoy,
    SplitterModule,
    Fractal,
    CrackShot,
    MicroRocketLauncher,
    AdaptiveShotgun,
    GuidedRound,
    //Cores
    Dash,
    GrapplingHook,
    SummonShield,
    Nanomachines,
    CreateFighter,
    Assault,
    Expose,

    End, //Used for enumeration
}
public enum Sprites
{
    Fighter,
    Player,
    Asteroid,
    Cruiser,
    Shotgunner,
    ShotgunShield,
    Mothership,
    Arrow,
    Sniper,
    Missile,
    PlayerGun,
    SymmetryBoss,
    OverloadBoss,
    OverloadShield,
    TurretBase,
    TurretHead,
    TurretTracker,
    Miner,
    Hovercraft,
    ExcursionBoss,
    Orbiter,
    WyvernBoss,
    AdvancedFighter,
    PickupDrone,
    Explosion,
    ExodusBoss,
    Healer,
    LargeMinerArm,
    LargeMiner,
    WarpGate,
    VeilBoss,
    InfernoBoss,
    FlareBoss,
    QuantumResonator,
    Communicator,
    Trader,
    MassRelayOne,
    MassRelayTwo,
    MassRelayThree,
    MassRelayFour,
    SurgeChild,
    SurgeBoss,
    Engineer,
    Wyrm,
    BloomHead,
    BloomBody,
    BloomTail,
    StreamlineBoss,
    StreamlineLeftWing,
    StreamlineRightWing,
    ClockworkBoss,
    Cog,
    DeadeyeBoss,
    ContinuumBoss,
    EpitomeOne,
    EpitomeTwo,
    EpitomeThree,
    DropPod,
    StealthFighter,
    Hunter,

    MetalScrap, RealMetalScrap,
    Hull, RealHull,
    Engines, RealEngines,
    Guns, RealGuns,
    MissileModule, RealMissileModule,
    SniperModule, RealSniperModule,
    Sensors, RealSensors,
    Core, RealCore,
    Trap, RealTrap,
    Barricade, RealBarricade,
    Bomb, RealBomb,
    Crossbow, RealCrossbow,
    Spiral, RealSpiral,
    Flamethrower, RealFlamethrower,
    SpecializedParts, RealSpecializedParts,
    Torch, RealTorch,
    Assault, RealAssault,
    Furnace, RealFurnace,
    Shield, RealShield,
    Lidar, RealLidar,
    Nanomachines, RealNanomachines,
    Expose, RealExpose,
    Stealth, RealStealth,
    Radar, RealRadar,
    GrapplingHook, RealGrapplingHook,
    Fireball, RealFireball,
    PrismArray, RealPrismArray,
    PulseEmitter, RealPulseEmitter,
    Ablative, RealAblative,
    Orion, RealOrion,
    Reflective, RealReflective,
    Work, RealWork,
    Plasma, RealPlasma,

    SpiralShot,
    PulseShot,
    Microshot,
    CrossbowShot,
    Explosive,

    Dot,
    Dollar,
    Circle,
    Glow,

    PlayerUI,
    Title,
    Button,
    LargePanel,
    GargantuanPanel,
    EmptySlot,
    SelectedTab,
    Tab,
    Knob,
    WideButton,
    ToggleButton,
    Terminal,
    Miniplayer,
    Textbox,
    Underlay,
    SwitchOne,
    SwitchTwo,
    SwitchThree,
    SwitchFour,
    SwitchFive,
    Overlay,
    Floppy,
    FloppyFlat,
    RightSideOpen,
    DeadFile,
    RightSidePanel,
    Dial,
    Indicator,
    LEDGlow,
    FuseDetailing,

    SmeltIcon,
    RepairIcon,
    VictoryIcon,
    PlayIcon,
    SettingsIcon,
    PlanetIcon,
    Fuse,
    FuseSlot,

    Cursor,
    ClickedCursor,
}
public enum Sound
{
    LMGFire,
    PulseFire,
    MissileFire,
    SniperFire,
    Explosion,
    ShotgunFire,

    Hit,
    ShieldHit,
    Death,

    Dock,
    Undock,
    Full,
    FireEngines,
    FireLaser,
    ComputerSounds,
    Beep,

    OpenMenu,
    CloseMenu,
    Interact,
    Click,
    Fail,

    main,
    boss,
    menu,
    secretBoss,
    finalBoss,
    None, //Used for missions w/o music
}
public enum Message
{
    MothershipCraftItem,
    MothershipUpdateFurnace,
    ToggleTerminal,
    RestartModules,
    EscapeDroneLeave,
    Hack,
}
public enum Condition
{
    None,
    Protect,
    Kill,
    CustomIncomplete,
    CustomComplete,
    DelayedSpawn,
}
public enum Binding
{
    Up,
    Down,
    Left,
    Right,
    Dock,
    Construct,
    SwapPrimary,
    OpenPanel,
    ToggleAimAssist,
    DropScrap,
    Ability,
    WarpForward,
    WarpBackward,
    SkipCutscene
}
public enum LoadingStage
{
    Preload,
    MainMenu,
    MissionSelect,
    Complete
}
